services:
  api01:
    build: ./01-api
    ports:
      - "8081:8080"
  
  api01-scan:
    build: 
      context: ./01-api
      dockerfile: Dockerfile-scan
    command: >
      sh -c "export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet sonarscanner begin /k:\"${SONAR_PROJECT_KEY}\" /o:\"${SONAR_ORGANIZATION}\" /d:sonar.token=\"${SONAR_TOKEN}\" /d:sonar.host.url=\"http://178.128.115.188:9000\" &&
         dotnet build ${SOLUTION_PATH} --no-incremental &&
         dotnet sonarscanner end /d:sonar.token=\"${SONAR_TOKEN}\""
