services:
  api01:
    build: ./01-api
    # ports:
    #   - "8081:8080"
  
  api01-scan:
    build: 
      context: ./01-api
      dockerfile: Dockerfile-scan
    command: >
      sh -c "export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet-sonarscanner begin /k:\"${SONAR_PROJECT_KEY}\" /o:\"${SONAR_ORGANIZATION}\" /d:sonar.token=\"${SONAR_TOKEN}\" /d:sonar.host.url=\"http://178.128.115.188:9000\" &&
         dotnet build ${SOLUTION_PATH} --no-incremental &&
         dotnet-sonarscanner end /d:sonar.token=\"${SONAR_TOKEN}\""

  scan-secret:
    image: zricethezav/gitleaks:latest
    volumes:
      - ./01-api:/app
    command: ["dir", "/app", "-v"]
  
  api-test:
    image: postman/newman
    volumes:
      - ./postman/json-placeholder.postman_collection.json:/etc/newman/1.json
    command: ["run", "/etc/newman/1.json"]
  
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ./openapi/:/zap/wrk/:rw
      - ./reports/:/zap/reports/:rw
    command: zap-api-scan.py -f openapi -t openapi.yml -r /zap/reports/report.html -x /zap/reports/report.xml
