# GitLab CI pipeline for building the 'api' service using Docker Compose in workshop/demo-secure-code

stages:
  - build

build-api:
  stage: build
  script:
    - cd workshop/demo-secure-code
    - docker compose build api
  only:
    - main
