# GitLab CI pipeline for building the 'api' service using Docker Compose in workshop/demo-secure-code

stages:
  - build
  - security

build-api:
  stage: build
  script:
    - cd workshop/demo-secure-code
    - docker compose build api
  only:
    - main

# Scan code with Gitleaks
gitleaks_scan:
  stage: security
  script:
    - docker run -v $(pwd):/src zricethezav/gitleaks detect --repo-path=/src --config=/src/gitleaks.toml --exit-code=1 # Scan the current repository, use a config file, and exit with an error code if leaks are found
  allow_failure: false # Prevent the pipeline from passing if leaks are found
