services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf  # Updated to point to the SSL config
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email example@gmail.com --agree-tos --no-eff-email --staging -d somkiat.tech  -d www.somkiat.tech

volumes: 
  web-root:
  certbot-etc:
  certbot-var:
