services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ./openapi/:/zap/wrk/:rw
      - ./reports/:/zap/reports/:rw
    command: zap-api-scan.py -f openapi -t juice_shop.yml -r /zap/reports/report.html -x /zap/reports/report.xml
    networks:
      - dast
  petclinic:
    image: springcommunity/spring-petclinic-rest
    ports:
      - "9966:9966"
    networks:
      - dast
  
  juice_shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - SESSION_SECRET=secret
      - SECURITY_ANSWER=secret
    networks:
      - dast

networks:
  dast:
    name: dast